# Generated by Django 2.2.3 on 2019-10-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190910_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
