# Generated by Django 2.2.3 on 2019-10-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_auto_20190909_1735'),
        ('payment', '0003_delete_orderlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ManyToManyField(related_name='order_p', to='selection.Orders'),
        ),
    ]
