# Generated by Django 2.2.3 on 2019-10-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20191001_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
