# Generated by Django 2.2.3 on 2019-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20191002_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
