# Generated by Django 2.2.3 on 2019-09-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothmenu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
