# Generated by Django 2.2.3 on 2019-08-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_auto_20190810_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothmenu',
            name='image',
            field=models.ImageField(default=1, upload_to='pics/ClothMenu'),
            preserve_default=False,
        ),
    ]
