# Generated by Django 2.2.3 on 2019-08-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_clothmenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='shirtfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirtfitd', to='selection.ShirtFit'),
        ),
    ]
