# Generated by Django 2.2.3 on 2019-08-24 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_design_shirtfit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back', to='selection.Back'),
        ),
        migrations.AlterField(
            model_name='design',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button', to='selection.Button'),
        ),
        migrations.AlterField(
            model_name='design',
            name='button_hole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttonhole', to='selection.ButtonHole'),
        ),
        migrations.AlterField(
            model_name='design',
            name='cloth_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothmenu', to='selection.ClothMenu'),
        ),
        migrations.AlterField(
            model_name='design',
            name='collar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar', to='selection.Collar'),
        ),
        migrations.AlterField(
            model_name='design',
            name='cuff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuff', to='selection.Cuff'),
        ),
        migrations.AlterField(
            model_name='design',
            name='front',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front', to='selection.Front'),
        ),
        migrations.AlterField(
            model_name='design',
            name='pocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pocket', to='selection.Pocket'),
        ),
        migrations.AlterField(
            model_name='design',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
