# Generated by Django 2.2.3 on 2019-07-30 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField()),
                ('back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_o', to='selection.Back')),
                ('cloth_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothmenu_o', to='selection.ClothMenu')),
                ('collar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar_o', to='selection.Collar')),
                ('cuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuff_o', to='selection.Cuff')),
                ('front', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_o', to='selection.Front')),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocket_o', to='selection.Pocket')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Measurement_o', to='selection.Measurement')),
                ('standard_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standardsize_o', to='selection.StandardSize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_o', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
